// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:59653459-03d2-450e-b659-70cf48a70b84",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wIMHQD594",
    "aws_user_pools_web_client_id": "2n34blsrt2bu3pnv7k3o6m4rf8",
    "aws_appsync_graphqlEndpoint": "https://4wenrdbqqncezlrbelfgqp5qi4.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "photoalbums0be9af16ceb24d0a90186f4fbc868abb",
    "aws_user_files_s3_bucket_region": "us-east-2",
    "aws_content_delivery_bucket": "photoalbums-20190116002958-hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://photoalbums-20190116002958-hostingbucket.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
